
export interface CardTheme {
  id: string;
  name: string;
  primary: string;
  secondary: string;
  accent: string;
  gradient: string;
  glow: string;
}

export interface CardData {
  from: string;
  to: string;
  relationship: string;
  wish: string;
  themeId: string;
  includeBlessing: boolean;
  addSurprise: boolean;
  blessingIndex?: number;
}

export const THEMES: CardTheme[] = [
  {
    id: 'crescent-dream',
    name: 'Crescent Dream',
    primary: '#1a0a3d',
    secondary: '#00D4FF',
    accent: '#FFD166',
    gradient: 'from-[#0a0515] via-[#1a0a3d] to-[#0d1f3f]',
    glow: 'rgba(0, 212, 255, 0.3)'
  },
  {
    id: 'lantern-glow',
    name: 'Lantern Glow',
    primary: '#2d1b0d',
    secondary: '#FF8C00',
    accent: '#FFD166',
    gradient: 'from-[#150a05] via-[#2d1b0d] to-[#3f1f0d]',
    glow: 'rgba(255, 140, 0, 0.3)'
  },
  {
    id: 'peaceful-garden',
    name: 'Peaceful Garden',
    primary: '#05150a',
    secondary: '#00B894',
    accent: '#FFFFFF',
    gradient: 'from-[#05150a] via-[#0a3d1a] to-[#0d3f1f]',
    glow: 'rgba(0, 184, 148, 0.3)'
  },
  {
    id: 'royal-purple',
    name: 'Royal Purple',
    primary: '#150515',
    secondary: '#FF6B9D',
    accent: '#FFD166',
    gradient: 'from-[#150515] via-[#3d0a3d] to-[#3f0d3f]',
    glow: 'rgba(255, 107, 157, 0.3)'
  }
];

export const PRESET_WISHES = [
  "May this Ramzan bring you peace, joy, and endless blessings, keeping you in my duas.",
  "May this Ramzan shine the light of guidance in your home and your heart forever.",
  "May this Ramzan fill your month with mercy and your heart with profound gratitude.",
  "May this Ramzan be the month Allah accepts your fasts and answers your secret prayers.",
  "May this Ramzan turn your heart into a vessel of Noor and fill your days with Barakah.",
  "May this Ramzan heal what is broken within you and strengthen what is weak.",
  "May this Ramzan bring you strength in every suhoor and peace in every iftar.",
  "May this Ramzan become the beautiful turning point you have been waiting for.",
  "May this Ramzan open the gates of Heaven for you and ensure the gates of Mercy never close.",
  "May this Ramzan grant you 30 days of clemency, 720 hours of enlightenment, and 43,200 minutes of joy.",
  "May this Ramzan deepen your connection with the Quran and fade your connection with sorrow.",
  "May this Ramzan wash away your worries and grant you a completely new beginning.",
  "May this Ramzan help you find Allah in every moment of silence and every moment of chaos.",
  "May this Ramzan remove the bitterness of your struggles with the sweetness of Iftar.",
  "May this Ramzan see your name called amongst those whom Allah loves most.",
  "May this Ramzan allow you to exit the month with a heart lighter than when you entered it.",
  "May this Ramzan bring you the clarity you seek and the peace you truly deserve.",
  "May this Ramzan reward your patience with a joy that makes you forget every tear.",
  "May this Ramzan bring you love, duas, and the warmest wishes for a blessed month.",
  "May this Ramzan protect your home with angels and fill your soul with serenity.",
  "May this Ramzan grant you the strength to forgive, the will to change, and the heart to love.",
  "May this Ramzan bring you closer to Allah than you have ever been before.",
  "May this Ramzan be a month of accepted prayers and completely forgiven sins.",
  "May this Ramzan let blessings cascade over your life like a beautiful waterfall.",
  "May this Ramzan guide your heart to find its home in the remembrance of Allah.",
  "May this Ramzan recharge your soul and illuminate your path forward.",
  "May this Ramzan grant you the kind of peace that makes the world feel quiet and your heart feel full.",
  "May this Ramzan ensure your duas traverse the seven heavens and return as miracles.",
  "May this Ramzan allow you to bloom in faith and kindness like never before.",
  "May this Ramzan bless you with a heart that beats for Him alone.",
  "May this Ramzan fill your table with food, but your heart with even more gratitude.",
  "May this Ramzan wash away the dust of your worries with the rain of mercy.",
  "May this Ramzan be as beautiful and radiant as the moon that heralds it.",
  "May this Ramzan reveal the answer to every prayer you were too afraid to speak out loud.",
  "May this Ramzan be a detox for your soul and a feast for your spirit.",
  "May this Ramzan wrap Allah’s mercy around you like a warm embrace.",
  "May this Ramzan bring you days of fasting and nights of weeping in joy before your Lord.",
  "May this Ramzan multiply your good deeds and subtract your sins to zero.",
  "May this Ramzan bring you health, happiness, and your highest rank in Jannah.",
  "May this Ramzan be the one that changes everything for the better in your life.",
  "May this Ramzan give you a spirit that never tires of worship and a heart that never tires of gratitude.",
  "May this Ramzan write your name among the Rayyan-enterers on the Day of Judgment.",
  "May this Ramzan make the Quran your companion and the Prophet (SAW) your guide.",
  "May this Ramzan see your name written in the list of the liberated souls.",
  "May this Ramzan allow your Iftars to be shared with loved ones and your Duas with the Ummah.",
  "May this Ramzan be free of distraction and full of pure devotion.",
  "May this Ramzan reflect the Noor of this month in your face and your character.",
  "May this Ramzan give you the strength to let go of everything that harms your soul.",
  "May this Ramzan replace your sadness with a happiness that makes you prostrate in thanks.",
  "May this Ramzan bring light to the soul who brings so much light into my life.",
  "May this Ramzan make your fasts easy, your prayers long, and your rewards endless.",
  "May this Ramzan ensure you walk out purified, protected, and elevated.",
  "May this Ramzan bless your family with unity, health, and unshakeable faith.",
  "May this Ramzan grant you the highest level of Jannah without accounting.",
  "May this Ramzan keep the peace of Fajr with you until the silence of Isha.",
  "May this Ramzan replace your thirst for water with a thirst for knowledge.",
  "May this Ramzan make you a source of goodness for everyone around you.",
  "May this Ramzan be a month where your heart is softened and your burden is lightened.",
  "May this Ramzan help you find comfort in the verses of the Quran and strength in your Sujood.",
  "May this Ramzan answer the prayers you make for others.",
  "May this Ramzan be a beautiful journey back to your Creator.",
  "May this Ramzan give you the courage to change and the discipline to maintain it.",
  "May this Ramzan let your tears in Tahajjud water the seeds of your future happiness.",
  "May this Ramzan grant you the Lailat-ul-Qadr and its thousand months of blessings.",
  "May this Ramzan protect you from eyes that envy and hearts that hate.",
  "May this Ramzan leave a permanent mark of goodness on your soul.",
  "May this Ramzan accept your charity and erase your sins.",
  "May this Ramzan help you find the sweetness of faith in every sip of water.",
  "May this Ramzan guide your heart to what is right and your feet to what is just.",
  "May this Ramzan be a month of divine interventions and spiritual breakthroughs.",
  "May this Ramzan bless you with the company of the righteous.",
  "May this Ramzan cleanse your heart of all malice and fill it with pure love.",
  "May this Ramzan repair your relationship with the Quran.",
  "May this Ramzan bring you a joy that starts in this world and continues into the Hereafter.",
  "May this Ramzan grant you the ability to turn your habits into acts of worship.",
  "May this Ramzan shower you with mercy from the first moon to the last.",
  "May this Ramzan fill your home with the fragrance of Jannah.",
  "May this Ramzan be the time you conquer your nafs and liberate your soul.",
  "May this Ramzan accept your sleep as worship and your silence as dhikr.",
  "May this Ramzan ensure you are forgiven before the month is over.",
  "May this Ramzan illuminate your heart with the light of guidance.",
  "May this Ramzan make miracles your daily routine.",
  "May this Ramzan bless you with a heart that trembles at His mention.",
  "May this Ramzan help you find peace in the promise of Allah.",
  "May this Ramzan bring you closer to the person Allah created you to be.",
  "May this Ramzan be a time of deep reflection and profound connection.",
  "May this Ramzan make your prayers the ladder that lifts you out of your difficulties.",
  "May this Ramzan grant you a heart that is content and a tongue moist with His name.",
  "May this Ramzan shield you from the fire and welcome you into the gardens of delight.",
  "May this Ramzan feel like a warm hug from the heavens.",
  "May this Ramzan renew your faith and revive your spirit.",
  "May this Ramzan grant you the best of this world and the Hereafter.",
  "May this Ramzan bless you with opportunities to do good that you never imagined.",
  "May this Ramzan make every second count for your eternity.",
  "May this Ramzan make your heart a mirror that reflects the beauty of Islam.",
  "May this Ramzan wrap you in Allah’s infinite compassion.",
  "May this Ramzan be the healing your soul has been crying out for.",
  "May this Ramzan bring blessings that flow like a river and peace that stands like a mountain.",
  "May this Ramzan insure Allah loves you, the angels love you, and the world loves you.",
  "May this Ramzan allow you to enter Eid with a heart as pure as a newborn.",
  "May this Ramzan ensure your light never dims."
];

export const BLESSINGS = [
  "May the light of this month find the cracks in your heart and fill them with unshakeable peace.",
  "I pray that every silent struggle you carry is answered with a mercy so vast it brings you to tears of joy.",
  "May your home be a sanctuary where angels love to visit and where love is the only language spoken.",
  "I asked Allah today to protect your smile and grant you the kind of serenity that the world can't take away.",
  "May your fasts be a shield for your soul and your prayers a bridge to everything your heart desires.",
  "May this Ramzan be the turning point where your heaviest burdens finally become your greatest strengths.",
  "I pray that as you break your fast, the sweetness of gratitude heals every bitterness you've endured this year.",
  "May your heart be so full of Noor that you become a light for everyone walking in the dark.",
  "Sending you a dua that reaches the highest heavens—may you never feel alone in your journey.",
  "May Allah whisper peace to your soul in the moments when the world feels a little too loud.",
  "Oh Allah, grant this soul a happiness that looks like light and feels like freedom.",
  "May you be protected from hearts that are not humble and eyes that are not kind.",
  "I pray that the Quran opens its secrets to you and becomes the spring of your heart.",
  "May Allah grant you a destiny far more beautiful than the one you have been dreaming of.",
  "May your tears of repentance wash away the dust of your sins and leave you gleaming.",
  "I pray that you are given the strength to forgive those who hurt you, just as you seek Allah's forgiveness.",
  "May the angels speak your name in the heavens with love and honor.",
  "May you find Allah in the stillness of the night and the chaos of the day.",
  "I pray that your rizq is blessed, your time is expanded, and your efforts are accepted.",
  "May Allah place a barrier between you and everything that displeases Him.",
  "May your heart remain soft in a world that tries to harden it.",
  "I pray that you are granted the company of the righteous in this life and the next.",
  "May Allah remove every obstacle between you and your entrance to Jannah.",
  "May your faith be taller than your fears and your trust deeper than your doubts.",
  "I pray that you are among those who walk across the Sirat like a flash of lightning.",
  "May Allah bless you with the intercession of the Prophet (SAW) on the Day of Judgment.",
  "May your limbs be active in worship and your heart be active in gratitude.",
  "I pray that you are given clarity where there is confusion and light where there is darkness.",
  "May Allah answer the prayers you are too shy to ask for but desperately need.",
  "May your presence be a comfort to the sorrowful and a joy to the weary.",
  "I pray that you are granted a tongue that never tires of remembering Allah.",
  "May Allah make you of those who are patient in adversity and grateful in prosperity.",
  "May your grave be a garden from the gardens of Paradise.",
  "I pray that the doors of mercy are swung wide open for you this month.",
  "May Allah fix the affairs of your life in ways you couldn't even plan.",
  "May you be gifted with a heart that sees the good in everything.",
  "I pray that you are protected from the whispers of Shaitan and the evil of envy.",
  "May Allah bless your parents and grant them health, happiness, and long life.",
  "May you be reunited with your loved ones in the shade of Allah's throne.",
  "I pray that your life is a testament to the beauty of Islam.",
  "May Allah grant you the sweetness of iman and the coolness of contentment.",
  "May you be raised with the truth-bearers and the martyrs.",
  "I pray that Allah suffices you and makes you independent of His creation.",
  "May your heart be cleansed of pride, jealousy, and hypocrisy.",
  "May Allah guide your children and make them the coolness of your eyes.",
  "I pray that you are granted a beautiful ending and a gentle soul-taking.",
  "May Allah replace what He has taken from you with something better.",
  "May you be among those who hear 'Salam' from the Lord of Peace.",
  "I pray that your book of deeds is given in your right hand.",
  "May Allah make the Quran a witness for you, not against you.",
  "May your solitude be filled with the presence of the Divine.",
  "I pray that you never lose hope in the infinite mercy of your Creator.",
  "May Allah bless you with knowledge that benefits and deeds that are accepted.",
  "May your character be beautified with the manners of the Prophet (SAW).",
  "I pray that you are shielded from the heat of the Day of Judgment.",
  "May Allah grant you the tawfeeq to wake up when others are sleeping.",
  "May your heart be attached to the Masjid and your soul attached to prayer.",
  "I pray that you are forgiven for the sins you know and the sins you forgot.",
  "May Allah make you a key to goodness and a lock to evil.",
  "May your trials be a means of purification and elevation.",
  "I pray that you are loved by the inhabitants of the Heavens.",
  "May Allah grant you the wisdom of Luqman and the patience of Ayyub.",
  "May you be safe from the suddenness of punishment and the withdrawal of blessings.",
  "I pray that your heart is never empty of the love of Allah.",
  "May Allah make you a beacon of hope for the hopeless.",
  "May your life be long in obedience and your deeds be sincere.",
  "I pray that you are granted the vision of Allah's Face in Jannah.",
  "May Allah make your heavy days light and your hard days easy.",
  "May you be among those who race towards forgiveness.",
  "I pray that your heart is preserved from the corruption of this world.",
  "May Allah bless you with friends who remind you of Him.",
  "May your sleep be rest for your body and worship for your soul.",
  "I pray that you are granted a heart that understands and ears that listen.",
  "May Allah make you content with His decree, whatever it may be.",
  "May you be protected from the anxiety of the future and the regret of the past.",
  "I pray that your wealth is purified through charity and your soul through prayer.",
  "May Allah grant you the ability to lower your gaze and guard your tongue.",
  "May your house be built in the highest level of Paradise.",
  "I pray that you are saved from the torment of the grave.",
  "May Allah bless you with a sincere repentance before death.",
  "May you be a source of shade for others on a sunny day.",
  "I pray that your tears are wiped away by the Hand of Mercy.",
  "May Allah grant you a heart that is submissive and humble.",
  "May your name be mentioned with kindness even after you are gone.",
  "I pray that you are granted the intercession of the Quran.",
  "May Allah fill your life with barakah in time, health, and wealth.",
  "May you be among the Sabiroon and the Shakiroon.",
  "I pray that your heart is knitted together with the threads of Taqwa.",
  "May Allah protect you from the evil of your own soul.",
  "May your path to Jannah be made easy and smooth.",
  "I pray that you drink from the Hauz-e-Kauthar from the Prophet's hand.",
  "May Allah grant you a resolution to your problems that leaves you awestruck.",
  "May you be among those who are light upon light.",
  "I pray that your faith remains steadfast in the face of trials.",
  "May Allah bless you with the sweetness of conversation with Him.",
  "May your heart be a vessel that carries only good.",
  "I pray that you are granted a life that is pleasing to your Lord.",
  "May Allah make you a leader of the righteous.",
  "May your every breath be a step towards His pleasure.",
  "I pray that you are reunited with the Prophet (SAW) in Al-Firdous."
];
